name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build -j

    - name: Test
      run: ctest --test-dir build --output-on-failure
